import { ApiError } from "../utils/ApiError.js";
import HallOfFame from "../models/HallOfFame.js";

export const createManualEntry = async (data, adminId) => {
  const { title, eventDate, winners } = data;

  if (!title) throw new ApiError(400, "Title is required for manual entry");
  if (!eventDate) throw new ApiError(400, "Event date is required");
  if (!winners || !winners.length) throw new ApiError(400, "At least one winner is required");

  // No need to verify students since details are manually entered

  try {
    const newEntry = await HallOfFame.create({
      eventType: "general",
      title,
      eventDate,
      winners,
      createdBy: adminId,
      isAutoGenerated: false,
    });
    return newEntry;
  } catch (err) {
    if (err.code === 11000) {
      throw new ApiError(409, "A Hall of Fame entry with this event already exists.");
    }
    throw err;
  }
};

export const getManualEntries = async (page = 1, limit = 10) => {
  const pageNum = parseInt(page);
  const limitNum = parseInt(limit);
  const skip = (pageNum - 1) * limitNum;

  const query = { eventType: "general" };

  const [entries, total] = await Promise.all([
    HallOfFame.find(query)
      .populate("winners.student", "name email profileImage")
      .populate("createdBy", "name")
      .sort({ eventDate: -1 })
      .skip(skip)
      .limit(limitNum),
    HallOfFame.countDocuments(query),
  ]);

  return {
    entries,
    pagination: {
      page: pageNum,
      limit: limitNum,
      total,
      pages: Math.ceil(total / limitNum) || 1,
    },
  };
};

export const getManualEntryById = async (id) => {
  const entry = await HallOfFame.findOne({ _id: id, eventType: "general" })
    .populate("winners.student", "name email profileImage");
  
  if (!entry) throw new ApiError(404, "Hall of Fame entry not found");
  return entry;
};

export const updateManualEntry = async (id, data) => {
  const entry = await HallOfFame.findOne({ _id: id, eventType: "general" });
  if (!entry) throw new ApiError(404, "Hall of Fame entry not found");

  const { title, eventDate, winners } = data;

  if (title) entry.title = title;
  if (eventDate) entry.eventDate = eventDate;
  
  if (winners && winners.length) {
    entry.winners = winners;
  }

  try {
    await entry.save();
  } catch (err) {
    if (err.code === 11000) {
      throw new ApiError(409, "A Hall of Fame entry with this event already exists.");
    }
    throw err;
  }
  return entry;
};

export const deleteManualEntry = async (id) => {
  const entry = await HallOfFame.findOneAndDelete({ _id: id, eventType: "general" });
  if (!entry) throw new ApiError(404, "Hall of Fame entry not found");
  return entry;
};

export default {
  createManualEntry,
  getManualEntries,
  getManualEntryById,
  updateManualEntry,
  deleteManualEntry,
};
