import { ApiError } from "../utils/ApiError.js";
import hallOfFameRepository from "../repository/hallOfFame.repository.js";
import tournamentRepository from "../repository/tournament.repository.js";
import examSessionRepository from "../repository/examSession.repository.js";
import OlympiadTest from "../models/OlympiadTest.js";
import EventRegistration from "../models/EventRegistration.js";

// Helper function to get prize based on position
const getPrizeForPosition = (position) => {
  const prizes = {
    1: "Gold Medal",
    2: "Silver Medal",
    3: "Bronze Medal",
  };
  return prizes[position] || `Position ${position}`;
};

// Automatically generate Hall of Fame entry for completed Tournaments and Olympiads
export const autoGenerateHallOfFame = async (eventType, eventId, topN = 3) => {
  if (eventType !== "tournament" && eventType !== "olympiad") {
    throw new ApiError(400, "Hall of Fame only supports Tournaments and Olympiads");
  }

  const eventModelMap = {
    tournament: "Tournament",
    olympiad: "OlympiadTest",
  };

  // Check if Hall of Fame entry already exists
  const existingEntry = await hallOfFameRepository.findOne({
    eventType,
    eventId,
  });

  if (existingEntry) {
    // Update existing entry instead of throwing error
    return await updateExistingHallOfFame(eventType, eventId, topN);
  }

  let event;
  let winners = [];
  let eventDate;
  let testId;
  let registeredStudentIds = null;

  if (eventType === "tournament") {
    event = await tournamentRepository.findById(eventId);
    if (!event) throw new ApiError(404, "Tournament not found");

    // Get winners from the final stage
    const finalStage = event.stages[event.stages.length - 1];
    if (!finalStage) throw new ApiError(400, "Tournament has no stages");
    
    testId = finalStage.test;
    eventDate = finalStage.endTime;
  } else if (eventType === "olympiad") {
    event = await OlympiadTest.findById(eventId);
    if (!event) throw new ApiError(404, "Olympiad not found");
    if (!event.testId) throw new ApiError(400, "Olympiad has no test mapped");

    testId = event.testId;
    eventDate = event.resultDeclarationDate || event.endTime || new Date();

    const registrations = await EventRegistration.find({
      eventType: "olympiad",
      eventId: eventId,
      paymentStatus: "completed",
    }).select("student").lean();
    registeredStudentIds = registrations.map((r) => r.student?.toString()).filter(Boolean);
    if (registeredStudentIds.length === 0) return null;
  }

  const query = {
    test: testId,
    status: "completed",
    score: { $ne: null },
  };
  if (registeredStudentIds) {
    query.student = { $in: registeredStudentIds };
  }

  const sessionsResult = await examSessionRepository.findAll(query, {
    page: 1,
    limit: 1000, // Get more to sort properly
    sortBy: "score",
    sortOrder: "desc",
  });

  // Sort by score desc, then by completion time (earlier is better)
  const sessions = sessionsResult.sessions
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return new Date(a.completedAt) - new Date(b.completedAt);
    })
    .slice(0, topN)
    .map(session => ({
      ...session.toObject(),
      student: session.student || { _id: session.student },
    }));

  winners = sessions.map((session, index) => ({
    position: index + 1,
    student: session.student._id,
    score: session.score || 0,
    prize: getPrizeForPosition(index + 1),
  }));

  if (winners.length === 0) {
    // Don't create entry if no winners yet
    return null;
  }

  return await hallOfFameRepository.create({
    eventType,
    eventId,
    eventModel: eventModelMap[eventType],
    winners,
    eventDate,
    createdBy: null,
    isAutoGenerated: true,
  });
};

// Update existing Hall of Fame entry with latest winners
const updateExistingHallOfFame = async (eventType, eventId, topN = 3) => {
  const entry = await hallOfFameRepository.findOne({
    eventType,
    eventId,
  });
  if (!entry) return null;

  let testId;
  let registeredStudentIds = null;

  if (eventType === "tournament") {
    const tournament = await tournamentRepository.findById(eventId);
    if (!tournament || tournament.stages.length === 0) return entry;
    const finalStage = tournament.stages[tournament.stages.length - 1];
    testId = finalStage.test;
  } else if (eventType === "olympiad") {
    const event = await OlympiadTest.findById(eventId);
    if (!event || !event.testId) return entry;
    testId = event.testId;

    const registrations = await EventRegistration.find({
      eventType: "olympiad",
      eventId: eventId,
      paymentStatus: "completed",
    }).select("student").lean();
    registeredStudentIds = registrations.map((r) => r.student?.toString()).filter(Boolean);
    if (registeredStudentIds.length === 0) return entry;
  } else {
    return entry;
  }

  const query = {
    test: testId,
    status: "completed",
    score: { $ne: null },
  };
  if (registeredStudentIds) {
    query.student = { $in: registeredStudentIds };
  }

  // Get all completed sessions for this test, sorted by score
  const sessionsResult = await examSessionRepository.findAll(query, {
    page: 1,
    limit: 1000, // Get more to sort properly
    sortBy: "score",
    sortOrder: "desc",
  });

  // Sort by score desc, then by completion time (earlier is better)
  const sessions = sessionsResult.sessions
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return new Date(a.completedAt) - new Date(b.completedAt);
    })
    .slice(0, topN)
    .map(session => ({
      ...session.toObject(),
      student: session.student || { _id: session.student },
    }));

  if (sessions.length === 0) return entry;

  // Update winners
  const winners = sessions.map((session, index) => ({
    position: index + 1,
    student: session.student._id,
    score: session.score || 0,
    prize: getPrizeForPosition(index + 1),
  }));

  entry.winners = winners;
  await hallOfFameRepository.updateById(entry._id, { winners });

  return entry;
};

const ensureHallOfFameGeneratedForCompletedEvents = async (eventType) => {
  const now = new Date();

  if (!eventType || eventType === "tournament") {
    const tournaments = await tournamentRepository.find(
      { isPublished: true, "stages.endTime": { $lte: now } },
      { sort: { updatedAt: -1 }, limit: 200 }
    );

    for (const tournament of tournaments) {
      const finalStage = tournament?.stages?.[tournament.stages.length - 1];
      if (!finalStage) continue;
      if (new Date(finalStage.endTime) > now) continue;

      try {
        await autoGenerateHallOfFame("tournament", tournament._id, 3);
      } catch (_) {
        // Ignore generation errors here to keep listing endpoint resilient
      }
    }
  }

  if (!eventType || eventType === "olympiad") {
    const olympiads = await OlympiadTest.find(
      {
        $or: [
          { resultDeclarationDate: { $lte: now } },
          { resultDeclarationDate: null, endTime: { $lte: now } },
        ],
      },
      null,
      { sort: { updatedAt: -1 }, limit: 200 }
    );

    for (const olympiad of olympiads) {
      if (!olympiad.testId) continue;
      try {
        await autoGenerateHallOfFame("olympiad", olympiad._id, 3);
      } catch (_) {
        // Ignore generation errors
      }
    }
  }
};

export const getHallOfFameEntries = async (options = {}) => {
  const { page = 1, limit = 10, eventType } = options;

  const query = { eventModel: { $in: ["Tournament", "OlympiadTest"] } };
  if (eventType) {
    if (eventType !== "tournament" && eventType !== "olympiad") {
      throw new ApiError(400, "Invalid event type. Only tournament and olympiad are supported.");
    }
    query.eventType = eventType;
  } else {
    query.eventType = { $in: ["tournament", "olympiad"] };
  }

  await ensureHallOfFameGeneratedForCompletedEvents(eventType);

  const pageNum = parseInt(page);
  const limitNum = parseInt(limit);
  const skip = (pageNum - 1) * limitNum;

  const [entries, total] = await Promise.all([
    hallOfFameRepository.find(query, {
      populate: [
        { path: "winners.student", select: "name email" },
        { path: "eventId", select: "title" },
      ],
      sort: { eventDate: -1 },
      skip,
      limit: limitNum,
    }),
    hallOfFameRepository.count(query),
  ]);

  return {
    entries,
    pagination: {
      page: pageNum,
      limit: limitNum,
      total,
      pages: Math.ceil(total / limitNum) || 1,
    },
  };
};

export default {
  autoGenerateHallOfFame,
  getHallOfFameEntries,
};

