import { ApiError } from "../utils/ApiError.js";
import hallOfFameRepository from "../repository/hallOfFame.repository.js";
import olympiadRepository from "../repository/olympiad.repository.js";
import tournamentRepository from "../repository/tournament.repository.js";
import examSessionRepository from "../repository/examSession.repository.js";

// Helper function to get prize based on position
const getPrizeForPosition = (position) => {
  const prizes = {
    1: "Gold Medal",
    2: "Silver Medal",
    3: "Bronze Medal",
  };
  return prizes[position] || `Position ${position}`;
};

// Automatically generate Hall of Fame entry for completed Olympiads and Tournaments
export const autoGenerateHallOfFame = async (eventType, eventId, topN = 3) => {
  if (!["olympiad", "tournament"].includes(eventType)) {
    throw new ApiError(400, "Hall of Fame only supports Olympiads and Tournaments");
  }

  const eventModelMap = {
    olympiad: "Olympiad",
    tournament: "Tournament",
  };

  // Check if Hall of Fame entry already exists
  const existingEntry = await hallOfFameRepository.findOne({
    eventType,
    eventId,
  });

  if (existingEntry) {
    // Update existing entry instead of throwing error
    return await updateExistingHallOfFame(eventType, eventId, topN);
  }

  let event;
  let winners = [];
  let eventDate;

  if (eventType === "olympiad") {
    event = await olympiadRepository.findById(eventId);
    if (!event) {
      throw new ApiError(404, "Olympiad not found");
    }

    // Get all completed exam sessions for this olympiad's test
    const sessionsResult = await examSessionRepository.findAll({
      test: event.test,
      status: "completed",
      score: { $ne: null },
    }, {
      page: 1,
      limit: topN,
      sortBy: "score",
      sortOrder: "desc",
    });

    // Sort by score desc, then by completion time (earlier is better)
    const sessions = sessionsResult.sessions.sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return new Date(a.completedAt) - new Date(b.completedAt);
    }).slice(0, topN);

    winners = sessions.map((session, index) => ({
      position: index + 1,
      student: session.student._id,
      score: session.score || 0,
      prize: getPrizeForPosition(index + 1),
    }));

    eventDate = event.endTime;
  } else if (eventType === "tournament") {
    event = await tournamentRepository.findById(eventId);
    if (!event) {
      throw new ApiError(404, "Tournament not found");
    }

    // Get winners from the final stage
    const finalStage = event.stages[event.stages.length - 1];
    if (!finalStage) {
      throw new ApiError(400, "Tournament has no stages");
    }

    const sessionsResult = await examSessionRepository.findAll({
      test: finalStage.test,
      status: "completed",
      score: { $ne: null },
    }, {
      page: 1,
      limit: 1000, // Get more to sort properly
      sortBy: "score",
      sortOrder: "desc",
    });

    // Sort by score desc, then by completion time (earlier is better)
    const sessions = sessionsResult.sessions
      .sort((a, b) => {
        if (b.score !== a.score) return b.score - a.score;
        return new Date(a.completedAt) - new Date(b.completedAt);
      })
      .slice(0, topN)
      .map(session => ({
        ...session.toObject(),
        student: session.student || { _id: session.student },
      }));

    winners = sessions.map((session, index) => ({
      position: index + 1,
      student: session.student._id,
      score: session.score || 0,
      prize: getPrizeForPosition(index + 1),
    }));

    eventDate = finalStage.endTime;
  }

  if (winners.length === 0) {
    // Don't create entry if no winners yet
    return null;
  }

  return await hallOfFameRepository.create({
    eventType,
    eventId,
    eventModel: eventModelMap[eventType],
    winners,
    eventDate,
    createdBy: null,
    isAutoGenerated: true,
  });
};

// Update existing Hall of Fame entry with latest winners
const updateExistingHallOfFame = async (eventType, eventId, topN = 3) => {
  const entry = await hallOfFameRepository.findOne({
    eventType,
    eventId,
  });
  if (!entry) return null;

  let testId;

  if (eventType === "olympiad") {
    const olympiad = await olympiadRepository.findById(eventId);
    if (!olympiad) return entry;
    testId = olympiad.test;
  } else if (eventType === "tournament") {
    const tournament = await tournamentRepository.findById(eventId);
    if (!tournament || tournament.stages.length === 0) return entry;
    const finalStage = tournament.stages[tournament.stages.length - 1];
    testId = finalStage.test;
  } else {
    return entry;
  }

  // Get all completed sessions for this test, sorted by score
  const sessionsResult = await examSessionRepository.findAll({
    test: testId,
    status: "completed",
    score: { $ne: null },
  }, {
    page: 1,
    limit: 1000, // Get more to sort properly
    sortBy: "score",
    sortOrder: "desc",
  });

  // Sort by score desc, then by completion time (earlier is better)
  const sessions = sessionsResult.sessions
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return new Date(a.completedAt) - new Date(b.completedAt);
    })
    .slice(0, topN)
    .map(session => ({
      ...session.toObject(),
      student: session.student || { _id: session.student },
    }));

  if (sessions.length === 0) return entry;

  // Update winners
  const winners = sessions.map((session, index) => ({
    position: index + 1,
    student: session.student._id,
    score: session.score || 0,
    prize: getPrizeForPosition(index + 1),
  }));

  entry.winners = winners;
  await hallOfFameRepository.updateById(entry._id, { winners });

  return entry;
};

export const getHallOfFameEntries = async (options = {}) => {
  const { page = 1, limit = 10, eventType } = options;

  const query = {};
  if (eventType) {
    if (!["olympiad", "tournament"].includes(eventType)) {
      throw new ApiError(400, "Invalid event type. Only olympiad and tournament are supported.");
    }
    query.eventType = eventType;
  }

  const pageNum = parseInt(page);
  const limitNum = parseInt(limit);
  const skip = (pageNum - 1) * limitNum;

  const [entries, total] = await Promise.all([
    hallOfFameRepository.find(query, {
      populate: [
        { path: "winners.student", select: "name email" },
        { path: "eventId", select: "title" },
      ],
      sort: { eventDate: -1 },
      skip,
      limit: limitNum,
    }),
    hallOfFameRepository.count(query),
  ]);

  return {
    entries,
    pagination: {
      page: pageNum,
      limit: limitNum,
      total,
      pages: Math.ceil(total / limitNum) || 1,
    },
  };
};

export default {
  autoGenerateHallOfFame,
  getHallOfFameEntries,
};

