import mongoose from "mongoose";

const hallOfFameSchema = new mongoose.Schema(
  {
    eventType: {
      type: String,
      enum: ["tournament", "olympiad", "general"],
      required: true,
    },
    eventId: {
      type: mongoose.Schema.Types.ObjectId,
      required: false,
      refPath: "eventModel",
    },
    eventModel: {
      type: String,
      enum: ["Tournament", "OlympiadTest", "StaticEvent"],
      required: false,
    },
    title: {
      type: String,
      trim: true,
    },
    winners: [
      {
        position: {
          type: Number,
          required: true,
          min: 1,
        },
        student: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
          required: false, // Made optional for manual entries
        },
        studentName: {
          type: String, // For manual entries
          trim: true,
        },
        profileImage: {
          type: String, // For manual entries
        },
        quote: {
          type: String, // For manual entries
          trim: true,
        },
        score: {
          type: Number,
          default: 0,
        },
        prize: {
          type: String,
          trim: true,
        },
      },
    ],
    eventDate: {
      type: Date,
      required: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
      default: null, // Auto-generated entries won't have createdBy
    },
    isAutoGenerated: {
      type: Boolean,
      default: true, // Mark auto-generated entries
    },
  },
  {
    timestamps: true,
  }
);

hallOfFameSchema.index(
  { eventType: 1, eventId: 1 },
  { unique: true, partialFilterExpression: { eventId: { $type: "objectId" } } }
);
hallOfFameSchema.index({ eventType: 1, eventDate: -1 });
hallOfFameSchema.index({ "winners.position": 1 });

export default mongoose.models.HallOfFame || mongoose.model("HallOfFame", hallOfFameSchema);

