import mongoose from "mongoose";

const hallOfFameSchema = new mongoose.Schema(
  {
    eventType: {
      type: String,
      enum: ["tournament", "olympiad"],
      required: true,
    },
    eventId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      refPath: "eventModel",
    },
    eventModel: {
      type: String,
      enum: ["Tournament", "OlympiadTest"],
      required: true,
    },
    winners: [
      {
        position: {
          type: Number,
          required: true,
          min: 1,
        },
        student: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
          required: true,
        },
        score: {
          type: Number,
          default: 0,
        },
        prize: {
          type: String,
          trim: true,
        },
      },
    ],
    eventDate: {
      type: Date,
      required: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
      default: null, // Auto-generated entries won't have createdBy
    },
    isAutoGenerated: {
      type: Boolean,
      default: true, // Mark auto-generated entries
    },
  },
  {
    timestamps: true,
  }
);

hallOfFameSchema.index({ eventType: 1, eventId: 1 }, { unique: true });
hallOfFameSchema.index({ eventType: 1, eventDate: -1 });
hallOfFameSchema.index({ "winners.position": 1 });

export default mongoose.models.HallOfFame || mongoose.model("HallOfFame", hallOfFameSchema);

