name: Deploy FirstEdu Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Copy files to EC2
      - name: Copy Project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "./*"
          target: "/home/ubuntu/firstedu-backend"

      # Deploy application
      - name: Deploy & Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            mkdir -p /home/ubuntu/firstedu-backend
            cd /home/ubuntu/firstedu-backend

            echo "Current files:"
            ls -la

            echo "${{ secrets.ENV_FILE }}" > .env

            npm install

            if pm2 describe backend > /dev/null; then
              pm2 restart backend
            else
              pm2 start src/server.js --name backend
            fi

            pm2 save

            sudo systemctl restart nginx

            echo "Deployment completed successfully"
